/* Generated by the Python-subset compiler */
#include <stdio.h>

int a = 0;
int b = 0;
int folded = 0;
int i = 0;

int square(int x);
int add(int x, int y);

int square(int x) {
    int _t23 = 0;

    _t23 = x * x;
    return _t23;
}

int add(int x, int y) {
    int _t24 = 0;

    _t24 = x + y;
    return _t24;
}

int main(void) {
    int _t1 = 0;
    int _t10 = 0;
    int _t11 = 0;
    int _t12 = 0;
    int _t13 = 0;
    int _t14 = 0;
    int _t15 = 0;
    int _t16 = 0;
    int _t17 = 0;
    int _t18 = 0;
    int _t19 = 0;
    int _t2 = 0;
    int _t20 = 0;
    int _t21 = 0;
    const char * _t22 = "";
    int _t3 = 0;
    int _t4 = 0;
    int _t5 = 0;
    double _t6 = 0.0;
    int _t7 = 0;
    int _t8 = 0;
    int _t9 = 0;

    _t1 = 10;
    a = _t1;
    _t2 = 4;
    b = _t2;
    _t3 = a + b;
    printf("%d\n", _t3);
    _t4 = a - b;
    printf("%d\n", _t4);
    _t5 = a * b;
    printf("%d\n", _t5);
    _t6 = ((double) a) / ((double) b);
    printf("%g\n", _t6);
    _t7 = 14;
    printf("%d\n", _t7);
    _t8 = 20;
    printf("%d\n", _t8);
    _t9 = 5;
    _t10 = square(_t9);
    printf("%d\n", _t10);
    _t11 = 10;
    _t12 = 20;
    _t13 = add(_t11, _t12);
    printf("%d\n", _t13);
    _t14 = a > b;
    if (!_t14) goto ifend_2;
    _t15 = 42;
    printf("%d\n", _t15);
ifend_2: ;
    _t16 = 3;
    i = _t16;
while_3: ;
    _t17 = 0;
    _t18 = i > _t17;
    if (!_t18) goto while_end_4;
    printf("%d\n", i);
    _t19 = 1;
    _t20 = i - _t19;
    i = _t20;
    goto while_3;
while_end_4: ;
    _t21 = 600;
    folded = _t21;
    printf("%d\n", folded);
    _t22 = "All tests passed!";
    printf("%s\n", _t22);
    return 0;
}
